public enum Axis
{
	NONE = 0,
	HORIZONTAL = 1,
	HORIZONTAL_POSITIVE = 2,
	HORIZONTAL_NEGATIVE = 4,
	VERTICAL = 8,
	VERTICAL_POSITIVE = 0x10,
	VERTICAL_NEGATIVE = 0x20,
	DEPTH = 0x40,
	DEPTH_POSITIVE = 0x80,
	DEPTH_NEGATIVE = 0x100
}
