public enum DeleteProfileStatus
{
	SUCCESS = 1,
	ALREADY_DELETED = 2,
	NOT_A_PROFILE_ACCOUNT = 3,
	OWNER_ID_NOT_FOUND = 4,
	PROFILE_NOT_OWNED_BY_THIS_OWNER = 5,
	PROFILE_NOT_FOUND = 6,
	PROFILE_CANNOT_BE_DELETED = 7,
	IN_SUFFICIENT_VCASH_FUNDS = 8,
	ERROR = 255
}
