using System.ComponentModel;

public enum FTUEEvent
{
	[Description("firstLaunch")]
	FIRST_LAUNCHED,
	[Description("ready")]
	READY,
	[Description("incompatibleErrorShown")]
	INCOMPATIBLE_ERROR_SHOWN,
	[Description("adDataStarted")]
	AD_DATA_STARTED,
	[Description("adDataCompleted")]
	AD_DATA_COMPLETED,
	[Description("loadFirstScene")]
	LOAD_FIRST_SCENE,
	[Description("loadProfileSelection")]
	LOAD_PROFILE_SELECTION,
	[Description("prefetchStart")]
	PREFETCH_STARTED,
	[Description("prefetchComplete")]
	PREFETCH_COMPLETED,
	[Description("clickedPlayAsGuest")]
	PLAY_AS_GUEST,
	[Description("login")]
	LOGIN,
	[Description("profileSelectionLoaded")]
	PROFILE_SELECTION_LOADED,
	[Description("firstSceneLoaded")]
	FIRST_SCENE_LOADED,
	[Description("step")]
	STEP,
	[Description("complete")]
	COMPLETED,
	[Description("characterCustomizationStarted")]
	CHARACTER_CUSTOMIZATION_STARTED,
	[Description("characterCompleteCustomization")]
	CHARACTER_CUSTOMIZATION_COMPLETED,
	[Description("characterNameStart")]
	CHARACTER_NAME_STARTED,
	[Description("characterNameComplete")]
	CHARACTER_NAME_COMPLETED,
	[Description("dragonSelected")]
	DRAGON_SELECTED,
	[Description("dragonNameAccepted")]
	DRAGON_NAME_ACCEPTED,
	[Description("userAgreementAccepted")]
	USER_AGREEMENT_ACCEPTED,
	[Description("dragonEggSelected")]
	DRAGON_EGG_SELECTED,
	[Description("firstFlight")]
	FIRST_FLIGHT,
	[Description("flightTutorialComplete")]
	FLIGHT_TUTORIAL_COMPLETE,
	[Description("collectTask")]
	COLLECT_TASK,
	[Description("cutsceneStarted")]
	CUTSCENE_STARTED,
	[Description("cutsceneEnded")]
	CUTSCENE_ENDED,
	[Description("offerClosed")]
	OFFER_CLOSED,
	[Description("forceCheckTokenStarted")]
	FORCECHECKTOKEN_STARTED,
	[Description("forceCheckTokenFailed")]
	FORCECHECKTOKEN_FAILED,
	[Description("loginChildStarted")]
	LOGINCHILD_STARTED,
	[Description("registerChildStarted")]
	REGISTERCHILD_STARTED,
	[Description("loginChildCompleted")]
	LOGINCHILD_COMPLETED,
	[Description("setAvatarCompleted")]
	SETAVATAR_COMPLETED,
	[Description("registerChildSuccess")]
	REGISTERCHILD_SUCCESS,
	[Description("registerChildFailed")]
	REGISTERCHILD_FAILED,
	[Description("getUserProfileByUserIdCompleted")]
	GETUSERPROFILEBYUSERID_COMPLETED,
	[Description("onCloseCustomization")]
	ONCLOSECUSTOMIZATION,
	[Description("profileCreated")]
	PROFILE_CREATED,
	[Description("goToGame")]
	GOTOGAME,
	[Description("onProfileSelectedFailed")]
	ONPROFILESELECTED_FAILED,
	[Description("onMoviePlayed")]
	ONMOVIEPLAYED,
	[Description("sceneLoaded")]
	SCENE_LOADED
}
