public enum MissionEvent
{
	TASK_STARTED,
	OFFER,
	OFFER_COMPLETE,
	COLLECTED,
	TASK_COMPLETE,
	TASK_FAIL,
	TASK_END,
	TASK_END_COMPLETE,
	MISSION_END,
	MISSION_END_COMPLETE,
	MISSION_COMPLETE,
	MISSION_REWARDS_COMPLETE,
	REFRESH_MISSIONS
}
