public enum UtStatus
{
	NO_ERROR = 0,
	ERROR_UNKNOWN = -1,
	ERROR_NOT_IMPLEMENTED = -2,
	ERROR_PARAMS = -3,
	ERROR_MEMORY = -4,
	ERROR_NOT_FOUND = -5,
	ERROR_OUT_OF_RANGE = -6,
	ERROR_INVALID_OPERATION = -7,
	ERROR_TYPE_MISMATCH = -8
}
